from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, HiddenField,\
    SelectMultipleField, FileField, validators
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')
    submit2 = SubmitField('Sign In', validators=[DataRequired()])


class SelectForm(FlaskForm):
    schedule_list = SelectField("Расписание", choices=[], validators=[DataRequired()])
    student_list = SelectField("Ученики", choices=[], validators=[DataRequired()])
    student_list3 = SelectField("Ученики", choices=[], validators=[DataRequired()])
    school_list = SelectField("Школы", choices=[], validators=[DataRequired()])
    class_list = SelectField("Классы", choices=[], validators=[DataRequired()])
    group_list = SelectField("Group", choices=[], validators=[DataRequired()])
    group_list2 = SelectField("Group", choices=[], validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    teacher_list = SelectField("Учителя", choices=[], validators=[DataRequired()])
    teacher_list2 = SelectField("Учителя", choices=[], validators=[DataRequired()])
    teacher_list3 = SelectField("Учителя", choices=[], validators=[DataRequired()])
    name = StringField("Имя", validators=[DataRequired()])
    email2 = StringField('Email', validators=[DataRequired(), Email()])
    subject = StringField("Предмет", validators=[DataRequired()])
    subject2 = StringField("Предмет", validators=[DataRequired()])
    surname = StringField("Фамилия", validators=[DataRequired()])
    patronymic = StringField("Отчество", validators=[DataRequired()])
    password = StringField("Пароль", validators=[DataRequired()])
    sex = SelectField("Group", choices=[("М", "М"), ("Ж", "Ж")], validators=[DataRequired()])
    student_list2 = SelectField("Ученики", choices=[], validators=[DataRequired()])
    class_list2 = SelectField("Классы", choices=[], validators=[DataRequired()])
    name2 = StringField("Имя", validators=[DataRequired()])
    surname2 = StringField("Фамилия", validators=[DataRequired()])
    patronymic2 = StringField("Отчество", validators=[DataRequired()])
    password2 = StringField("Пароль", validators=[DataRequired()])
    sex2 = SelectField("Group", choices=[("М", "М"), ("Ж", "Ж")], validators=[DataRequired()])
    submit = SubmitField('Далее', validators=[DataRequired()])
    submit2 = SubmitField('Добавить', validators=[DataRequired()])
    submit3 = SubmitField('Добавить', validators=[DataRequired()])
    submit4 = SubmitField('Добавить', validators=[DataRequired()])
    ff = FileField('Добавить', validators=[DataRequired()])
    a1 = SelectMultipleField("Group", choices=[("М", "М"), ("Ж", "Ж")], validators=[DataRequired()])


class ScheduleForm(FlaskForm):
    monday1 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    monday2 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    monday3 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    monday4 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    monday5 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    monday6 = SelectField("Понедельник1", choices=[], validators=[DataRequired()])
    tuesday1 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    tuesday2 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    tuesday3 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    tuesday4 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    tuesday5 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    tuesday6 = SelectField("Вторник", choices=[], validators=[DataRequired()])
    wednesday1 = SelectField("Среда", choices=[], validators=[DataRequired()])
    wednesday2 = SelectField("Среда", choices=[], validators=[DataRequired()])
    wednesday3 = SelectField("Среда", choices=[], validators=[DataRequired()])
    wednesday4 = SelectField("Среда", choices=[], validators=[DataRequired()])
    wednesday5 = SelectField("Среда", choices=[], validators=[DataRequired()])
    wednesday6 = SelectField("Среда", choices=[], validators=[DataRequired()])
    thursday1 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    thursday2 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    thursday3 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    thursday4 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    thursday5 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    thursday6 = SelectField("Четверг", choices=[], validators=[DataRequired()])
    friday1 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    friday2 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    friday3 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    friday4 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    friday5 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    friday6 = SelectField("Пятница", choices=[], validators=[DataRequired()])
    saturday1 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    saturday2 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    saturday3 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    saturday4 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    saturday5 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    saturday6 = SelectField("Суббота", choices=[], validators=[DataRequired()])
    sunday1 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])
    sunday2 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])
    sunday3 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])
    sunday4 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])
    sunday5 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])
    sunday6 = SelectField("Воскресенье", choices=[], validators=[DataRequired()])

    submit = SubmitField('Добавить', validators=[DataRequired()])


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')


class EmailForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    email2 = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Далее', validators=[DataRequired()])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')


class CallsForm(FlaskForm):
    pnonest1 = StringField("Понедельник1",
            validators=[validators.Length(min=4, max=5)])
    pnonest2 = StringField("Понедельник1",  validators=[validators.Length(min=4, max=5),
                                                        DataRequired()])
    pnonest3 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonest4 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonest5 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonest6 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    pnonefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    pntwofn6 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest1 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest2 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest3 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest4 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest5 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonest6 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    vtonefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    vttwofn6 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest1 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest2 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest3 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest4 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest5 = StringField("Понедельник1",  validators=[DataRequired()])
    sronest6 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    sronefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    srtwofn6 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest1 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest2 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest3 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest4 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest5 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonest6 = StringField("Понедельник1",  validators=[DataRequired()])

    ctonefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    ctonefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    cttwofn6 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest1 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest2 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest3 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest4 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest5 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonest6 = StringField("Понедельник1",  validators=[DataRequired()])

    ptonefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    ptonefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    pttwofn6 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest1 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest2 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest3 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest4 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest5 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonest6 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn1 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn2 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn3 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn4 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn5 = StringField("Понедельник1",  validators=[DataRequired()])
    sbonefn6 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost1 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost2 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost3 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost4 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost5 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwost6 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn1 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn2 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn3 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn4 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn5 = StringField("Понедельник1",  validators=[DataRequired()])
    sbtwofn6 = StringField("Понедельник1",  validators=[DataRequired()])

    hidden_form = HiddenField("Explicit")

    submit = SubmitField('Добавить', validators=[DataRequired()])