"""empty message

Revision ID: 9c7a06c08b8a
Revises: c3a94851408f
Create Date: 2020-04-18 14:24:02.182213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7a06c08b8a'
down_revision = 'c3a94851408f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('group_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'])
    op.drop_table('students_group')
    # ### end Alembic commands ###
